# Generated by Django 6.0.1 on 2026-01-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('CORTE', 'Corte Láser'), ('SOLDADURA', 'Soldadura'), ('MECANIZADO', 'Mecanizado'), ('OTROS', 'Otros')], default='CORTE', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinaria/')),
                ('specs', models.CharField(blank=True, help_text='Ej: 6000W, 5 Ejes, etc.', max_length=200)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Maquinaria',
                'ordering': ['orden'],
            },
        ),
    ]
