# Generated by Django 6.0.1 on 2026-02-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIurrelan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='categoria',
            field=models.CharField(choices=[('CORTE', 'Corte Láser'), ('SOLDADURA', 'Soldadura'), ('MECANIZADO', 'Mecanizado'), ('OTROS', 'Auxiliares')], default='CORTE', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinaria/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de aparición', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='specs',
            field=models.CharField(blank=True, help_text='Ej: 6000W, 5 Ejes, etc.', max_length=200, verbose_name='Especificaciones'),
        ),
    ]
