# Generated by Django 6.0.1 on 2026-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIurrelan', '0002_alter_maquina_categoria_alter_maquina_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='categoria',
            field=models.CharField(choices=[('CORTE', 'Corte Láser'), ('SOLDADURA', 'Soldadura'), ('GRANALLADO', 'Granallado')], default='CORTE', max_length=20, verbose_name='Categoría'),
        ),
    ]
